export { default as Body1 } from './Body1'
export { default as Body2 } from './Body2'
export { default as H1 } from './H1'
export { default as H2 } from './H2'
export { default as LabelDescription } from './LabelDescription'
export { default as Label } from './Label'
