export { default as VerifiedArtist } from './verified-artist.svg'
export { default as HeartWithCircleBg } from './heart-w-circle-bg.svg'
export { default as Facebook } from './facebook.svg'
export { default as Twitter } from './twitter.svg'
export { default as Instagram } from './instagram.svg'
export { default as LinkedIn } from './linkedin.svg'
