export { default as Play } from './play.svg'
export { default as Pause } from './pause.svg'
export { default as Replay } from './replay.svg'
export { default as Rewind } from './rewind.svg'
export { default as Shuffle } from './shuffle.svg'
